extends GutTest

var control: LayerableControl = null

func test_general():
	var control_1 := Control.new()
	var control_2 := Control.new()
	var control_3 := Control.new()
	control = LayerableControl.new()
	control.add_child(control_1)
	assert_eq(control.get_layer_count(), 0, "Unexpected layer count")
	assert_eq(control.get_stack_count(), 0, "Unexpected stack count")
	add_child(control)
	assert_eq(control.get_layer_count(), 1, "Unexpected layer count")
	assert_eq(control.get_stack_count(), 0, "Unexpected stack count")
	control.add_child(control_2)
	assert_eq(control.get_layer_count(), 2, "Unexpected layer count")
	assert_eq(control.get_stack_count(), 0, "Unexpected stack count")
	control.add_child(control_3)
	assert_eq(control.get_layer_count(), 3, "Unexpected layer count")
	assert_eq(control.get_stack_count(), 0, "Unexpected stack count")
	assert_eq(control.get_location_in_all(control_1.get_instance_id()), 0, "Unexpected index result")
	assert_eq(control.get_location_in_all(control_2.get_instance_id()), 1, "Unexpected index result")
	assert_eq(control.get_location_in_all(control_3.get_instance_id()), 2, "Unexpected index result")
	control.remove_child(control_2)
	assert_eq(control.get_layer_count(), 2, "Unexpected layer count")
	assert_eq(control.get_location_in_all(control_2.get_instance_id()), -1, "Unexpected index result")
	control_2.free()
	assert_eq(control.get_stack_count(), 0, "Unexpected stack count")
	assert_eq(control.get_location_in_stack(control_3.get_instance_id()), -1, "Unexpected index result")
	assert_eq(control.push_by_id(control_3.get_instance_id()), true, "Unexpected push result")
	assert_eq(control.get_location_in_stack(control_3.get_instance_id()), 0, "Unexpected index result")
	assert_eq(control.get_layer_count(), 2, "Unexpected layer count")
	assert_eq(control.get_stack_count(), 1, "Unexpected stack count")
	assert_eq(control.pop_by_id(control_1.get_instance_id()), false, "Unexpected pop result")
	assert_eq(control.get_layer_count(), 2, "Unexpected layer count")
	assert_eq(control.get_stack_count(), 1, "Unexpected stack count")
	assert_eq(control.pop_by_id(control_3.get_instance_id()), true, "Unexpected pop result")
	assert_eq(control.get_layer_count(), 2, "Unexpected layer count")
	assert_eq(control.get_stack_count(), 0, "Unexpected stack count")
	assert_eq(control.push_by_name(control_1.name), true, "Unexpected push result")
	assert_eq(control.pop_by_name(control_1.name), true, "Unexpected pop result")
	assert_eq(control.get_location_in_stack(control_1.get_instance_id()), -1, "Unexpected index result")
	assert_eq(control.auto_push(), true, "Unexpected push result")
	assert_eq(control.get_location_in_stack(control_1.get_instance_id()), 0, "Unexpected index result")
	assert_eq(control.auto_pop(), true, "Unexpected pop result")
	assert_eq(control.get_location_in_stack(control_1.get_instance_id()), -1, "Unexpected index result")
	assert_eq(control.auto_pop(), false, "Unexpected pop result")
	assert_eq(control.get_location_in_stack(control_1.get_instance_id()), -1, "Unexpected index result")
	remove_child(control)
	control.free()
	control = null
